### ISSUE TITLE
Discord SRV Issue. 

### ISSUE THREAD

**Issue by Pikaronga** [Tanguygab/TAB-Additions#12]
Discord SRV doesn't work with TAB-additions as chat handler. Even with:

DiscordSRV-Support: true

It doesn't work. Discord SRV in debug mode says that the chat event gets cancelled so it's on your end.

**Comment by Tanguygab** [comment]
Yup, it is cancelled because I can't really do it otherwise, though I should have added support for it, what's your TAB-Additions version?
In newer versions, that part of the config changed 
![image](https://user-images.githubusercontent.com/45695833/163215467-dd12ea8d-7bd6-4721-82fd-ea83e6220e59.png)

**Comment by Pikaronga** [comment]
> 

i'm on the latest version but i guess it doesn't outo update?

**Comment by Pikaronga** [comment]
could u send that part in text so i can copy in it

**Comment by Pikaronga** [comment]
okay yeah adding that to the chat file works perfectly fine. Thanks for the help!
